ZooGuard.Web/Areas/Admin/Controllers/SpecialityWorkerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ZooGuard.Core.Interfaces.InterfaciesForWorkerServicies;

namespace ZooGuard.Web.Areas.Admin.Controllers
{
    [Area("admin")]
    public class SpecialityWorkerController : Controller
    {
        private readonly ISpecialityWorkerService workerSpecialityService;

        public SpecialityWorkerController(ISpecialityWorkerService workerSpecialityService)
        {
            this.workerSpecialityService = workerSpecialityService;
        }

        [HttpGet("spc")]
        public async Task<IActionResult> Speciality()
        {
            var list = await workerSpecialityService.GetAllAsync();

            if (list.Count < 1)
            {
                return RedirectToAction("SpecialityListEmpty");
            }
            return View("Specialty", list);
        }

        [HttpGet("spc/emp")]
        public IActionResult SpecialityListEmpty()
        {
            return View("SpecialityListEmpty");
        }

        [HttpGet("spc/ad")]
        public IActionResult GetFormAddSpeciality()
        {
            return View("GetFormAddSpeciality");
        }
    }
}

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/GetFormAddSpeciality.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/Speciality.cshtml
@model IList<ZooGuard.Core.Entities.WorkerEntities.SpecialityWorker>
@{
    ViewData["Title"] = "Speciality Table";
}

@await Html.PartialAsync("SpecialityNavBarPartial")

<div class = "tabs">

@await Html.PartialAsync("SpecialityMarkPartial")

<table class="table table-hover">

    @await Html.PartialAsync("SpecialityTheadTablePartial")

  <tbody>    
        @foreach(var line in @Model)
        {
            <tr class="row-table table-light">
                <th class="border-top-0 border-info border-left"><i class="fa fa-times fa-lg btn btn-danger alert-secondary"></i>&ensp;&ensp;<i class="fa fa-pencil fa-lg btn btn-info alert-secondary"></i></th>
                <td><button type="submit" class="btn btn-info">@line.Name</button></td>
                <td>@line.Description</td>

                    @if(@line.SpecialitiesOfWorkers.Count() == 0)
                    {
                        <td><button type="submit" class="btn btn-secondary" disabled>Positions (@line.SpecialitiesOfWorkers.Count())</button></td>
                    }
                    else
                    {
                        <td><button type="submit" class="btn btn-info">Positions (@line.SpecialitiesOfWorkers.Count())</button></td>
                    }
            </tr>
        }
</tbody>
</table>
</div>

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/SpecialityListEmpty.cshtml
@{
    ViewData["Title"] = "Speciality Empty";
}

    @await Html.PartialAsync("SpecialityNavBarPartial")
    
    @await Html.PartialAsync("SpecialityMarkPartial")

    <h3 class="mt-5">The list is empty</h3>

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/SpecialityMarkPartial.cshtml
<ul class="nav nav-tabs border-bottom border-info">
      <li>
        <a class="nav-link pl-4" data-toggle="tab"></a>
      </li>
      <li>
        <a class="nav-link" data-toggle="tab" href="~/wk">Workers</a>
      </li>
      <li class="nav-item border-bottom border-light">
        <a class="nav-link active border-bottom-0 border-info" data-toggle="tab" href="~/spc">Speciality</a>
      </li>
    </ul>

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/SpecialityNavBarPartial.cshtml
<nav class=" second-navbar row" style="color: #f6f6f6;">  
     <il class="nav-item col-2 pt-2 mt-1 mr-3">
        <div class="addres-link"><p><a href="~/hm">Home</a>&#47;Speciality</p></div>
     </il>
     <il class="nav-item col-auto">
     </il>
     <il class="nav-item col-auto">
         <nav class="row">
         <form asp-area="admin" asp-controller="Worker" asp-action="GetFormAddWorker" method="get" class="col-auto m-0 pr-0">
         <button type="submit" class="btn btn-info rounded-left float-left">Add Worker</button>
         </form>
         
         <form asp-area="admin" asp-controller="SpecialityWorker" asp-action="GetFormAddSpiciality" method="get" class="col-auto m-0 pl-1">
         <button class="btn btn-info rounded-left float-left" type="submit">Add Speciality</button>
         </form>
         </nav>
     </il>
</nav>

ZooGuard.Web/Areas/Admin/Views/SpecialityWorker/SpecialityTheadTablePartial.cshtml
<thead>
    <tr class="table-light">
      <th scope="col" class="border-info border-left border-top-0"></th>
      <th scope="col" class="border-info border-top-0">Name</th>
      <th scope="col" class="border-info border-top-0">PM</th>
      <th scope="col" class="border-info border-top-0">Company</th>
      <th scope="col" class="border-info border-top-0">Positions</th>
      <th scope="col" class="border-info border-top-0">Places</th>
      <th scope="col" class="border-info border-top-0 border-right">Worker</th>
    </tr>
  </thead>