ZooGuard.Web/Areas/Admin/Controllers/PlaceController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ZooGuard.Core.Entities.StorageEntities;
using ZooGuard.Core.Interfaces;
using ZooGuard.Web.Interfaces.InterfacesForStorageViewModelServices;

namespace ZooGuard.Web.Areas.Admin.Controllers
{
    [Area("admin")]
    public class PlaceController : Controller
    {
        private readonly IAllStorageService<Place> placeService;
        private readonly IPlaceViewModelService placeViewModelService;

        public PlaceController(IAllStorageService<Place> placeService, IPlaceViewModelService placeViewModelService)
        {
            this.placeService = placeService;
            this.placeViewModelService = placeViewModelService;
        }

        [HttpGet("pl")]
        public async Task<IActionResult> Places()
        {
            var list = await placeService.GetAllAsync();

            if (list.Count < 1)
            {
                return RedirectToAction("PlaceListEmpty");
            }
            return View("Places", list);
        }

        [HttpGet("pl/emp")]
        public IActionResult PlaceListEmpty()
        {
            return View("PlaceListEmpty");
        }

        [HttpGet("pl/ad")]
        public IActionResult GetFormAddPlace()
        {
            var model = placeViewModelService.GetEmpty();

            return View("GetFormAddPlace", model);
        }
    }
}

ZooGuard.Web/Areas/Admin/Views/Place/GetFormAddPlace.cshtml
@model AddCompanyViewModel
@{
    ViewData["Title"] = "Add Place";
}
<form asp-area="admin" asp-controller="Place" asp-action="AddPlace" method="post" class="mt-5">
  <div class="form-row mb-0">
    <div class="form-group col-md-2">
      <label asp-for="Name" for="inputName"></label>
      <input asp-for="Name" type="text" class="form-control" id="inputOrgForm" placeholder="OOO">
    </div>
    <div class="form-group col-md-5">
      <label asp-for="Adress" for="inputName4"></label>
      <input asp-for="Adress" type="text" class="form-control" id="inputName" placeholder="Acme">
    </div>
  <div class="form-group col-md-5">
      <label asp-for="Characteristic" for="inputPassword4"></label>
      <input asp-for="Characteristic" class="form-control" id="inputUNP" placeholder="123456789">
    </div>
  </div>
<button type="submit" class="btn btn-info">Add Place</button>
</form>

ZooGuard.Web/Areas/Admin/Views/Place/PlaceListEmpty.cshtml
@{
    ViewData["Title"] = "Place Empty";
}

    @await Html.PartialAsync("PlaceNavBarPartial")
    
    @await Html.PartialAsync("PlaceMarkPartial")

    <h3 class="mt-5">The list is empty</h3>

ZooGuard.Web/Areas/Admin/Views/Place/PlaceMarkPartial.cshtml
<ul class="nav nav-tabs border-bottom border-info">
      <li>
        <a class="nav-link pl-4" data-toggle="tab"></a>
      </li>
      <li class="nav-item border-bottom border-light">
        <a class="nav-link active border-bottom-0 border-info" data-toggle="tab" href="~/pl">Places</a>
      </li>
    </ul>

ZooGuard.Web/Areas/Admin/Views/Place/PlaceNavBarPartial.cshtml
<nav class="second-navbar row" style="color: #f6f6f6;">  
     <il class="nav-item col-2 pt-2 mt-1 mr-3">
        <div class="addres-link"><p><a href="~/hm">Home</a>&#47;Companies</p></div>
     </il>
     <il class="nav-item col-auto">
     </il>
     <il class="nav-item col-auto">
         <nav class="row">
         <form asp-area="admin" asp-controller="Place" asp-action="GetFormAddPlace" method="get" class="col-auto m-0 pr-0">
         <button type="submit" class="btn btn-info rounded-left float-left">Add Place</button>
         </form>
         </nav>
     </il>
</nav>

ZooGuard.Web/Areas/Admin/Views/Place/Places.cshtml
@model IList<ZooGuard.Core.Entities.StorageEntities.Place>
@{
    ViewData["Title"] = "Place Table";
}

@await Html.PartialAsync("PlaceNavBarPartial")

<div class = "tabs">

    @await Html.PartialAsync("PlaceMarkPartial")

<table class="table table-hover">

    @await Html.PartialAsync("PlaceTheadTablePartial")

<tbody>    
        @foreach(var line in @Model)
        {
            <tr class="row-table table-light">
            <th scope="row" class="border-top-0 border-info border-left"><i class="fa fa-times fa-lg btn btn-danger alert-secondary"></i>&ensp;&ensp;<i class="fa fa-pencil fa-lg btn btn-info alert-secondary"></i></th>
            <td><button type="submit" class="btn btn-info">@line.Name</button></td>
            <td>@line.ActualAddress</td>
            <td>@line.Characteristic</td>
            <td>@line.Company.Name</td>
            <td>@line.Worker.LastName @line.Worker.Name @line.Worker.Patronymic</td>
                    @if(@line.Positions.Count() == 0)
                    {
                        <td><button type="submit" class="btn btn-secondary" disabled>Positions (@line.Positions.Count())</button></td>
                    }
                    else
                    {
                        <td><button type="submit" class="btn btn-info">Positions (@line.Positions.Count())</button></td>
                    }
            </tr>
        }
</tbody>
</table>
</div>