ZooGuard.Web/Areas/Admin/Controllers/WorkerController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using ZooGuard.Core.Interfaces.InterfaciesForWorkerServicies;

namespace ZooGuard.Web.Areas.Admin.Controllers
{
    [Area("admin")]
    public class WorkerController : Controller
    {
        private readonly IWorkerService workerService;

        public WorkerController(IWorkerService workerService)
        {
            this.workerService = workerService;
        }

        [HttpGet("wk")]
        public async Task<IActionResult> Worker()
        {
            var list = await workerService.GetAllAsync();

            if(list.Count < 1)
            {
                return View("WorkerListEmpty");
            }
            return View("Workers");
        }
    }
}

ZooGuard.Web/Areas/Admin/Views/Worker/WorkerListEmpty.cshtml
@{
    ViewData["Title"] = "Worker Empty";
}
    @await Html.PartialAsync("WorkerNavBarPartial")

    @await Html.PartialAsync("WorkerMarkPartial")

    <h3 class="mt-5">The list is empty</h3>

ZooGuard.Web/Areas/Admin/Views/Worker/WorkerMarkPartial.cshtml
    <ul class="nav nav-tabs border-bottom border-info">
      <li>
        <a class="nav-link pl-4" data-toggle="tab"></a>
      </li>
      <li class="nav-item border-bottom border-light">
        <a class="nav-link active border-bottom-0 border-info" data-toggle="tab" href="~/wk">Workers</a>
      </li>
      <li>
        <a class="nav-link" data-toggle="tab" href="~/spc">Speciality</a>
      </li>
    </ul>

ZooGuard.Web/Areas/Admin/Views/Worker/WorkerNavBarPartial.cshtml
 <nav class="second-navbar row" style="color: #f6f6f6;">  
     <il class="nav-item col-2 pt-2 mt-1 mr-3">
        <div class="addres-link"><p><a href="~/hm">Home</a>&#47;Workers</p></div>
     </il>
     <il class="nav-item col-auto">
     </il>
     <il class="nav-item col-auto">
         <nav class="row">
         <form asp-area="admin" asp-controller="Worker" asp-action="GetFormAddWorker" method="get" class="col-auto m-0 pr-0">
         <button type="submit" class="btn btn-info rounded-left float-left">Add Worker</button>
         </form>
         
         <form asp-area="admin" asp-controller="Specialty" asp-action="GetFormAddSpecialty" method="get" class="col-auto m-0 pl-1">
         <button class="btn btn-info rounded-left float-left" type="submit">Add Speciality</button>
         </form>
         </nav>
     </il>
</nav>

ZooGuard.Web/Areas/Admin/Views/Worker/WorkerTheadTablePartial.cshtml
 <thead>
    <tr class="table-light">
      <th scope="col" class="border-info border-left border-top-0"></th>
      <th scope="col" class="border-info border-top-0">Name</th>
      <th scope="col" class="border-info border-top-0">Speciality</th>
      <th scope="col" class="border-info border-top-0">Place</th>
      <th scope="col" class="border-info border-top-0">Company</th>
      <th scope="col" class="border-info border-top-0">Project</th>
      <th scope="col" class="border-info border-top-0">Positions</th>
      <th scope="col" class="border-info border-top-0">Storages</th>
      <th scope="col" class="border-info border-top-0 border-right">Server Rooms</th>
    </tr>
  </thead>

ZooGuard.Web/Areas/Admin/Views/Worker/Workers.cshtml
@model IList<ZooGuard.Core.Entities.WorkerEntities.Worker>
@{
    ViewData["Title"] = "Worker Table";
}

@await Html.PartialAsync("WorkerNavBarPartial")

<div class = "tabs">

    @await Html.PartialAsync("WorkerMarkPartial")

<table class="table table-hover">

    @await Html.PartialAsync("WorkerTheadTablePartial")

<tbody>    
        @foreach(var line in @Model)
        {
            <tr class="row-table table-light">
                <th scope="row" class="border-top -0 border-info border-left"><i class="fa fa-times fa-lg btn btn-danger alert-secondary"></i>&ensp;&ensp;<i class="fa fa-pencil fa-lg btn btn-info alert-secondary"></i></th>
                <td><button type="submit" class="btn btn-info">@line.Name @line.LastName @line.Patronymic</button></td>
            
                if(@line.SpecialitiesOfWorkers.Count() == 1) 
                {
                    <td>@line.SpecialitiesOfWorkers.Select(p => p.SpecialityWorker.Name)</td>
                }
                else
                {
                    <td><button type="submit" class="btn btn-info">Speciality(@line.SpecialitiesOfWorkers.Count())</button></td>
                }
            
                <td>@line.Place.Name</td>
            
                if(@line.WorkersInCompanies.Count() == 1) 
                {
                    <td><button type="submit" class="btn btn-info">@line.WorkersInCompanies.Select(p => p.Company.Name)</button></td>
                }
                else
                {
                    <td><button type="submit" class="btn btn-info">Companies(@line.WorkersInCompanies.Count())</button></td>
                }
            
                if(@line.WorkersInProjects.Count() == 1) 
                {
                    <td><button type="submit" class="btn btn-info">@line.WorkersInProjects.Select(p => p.Project.Name)</button></td>
                }
                else
                {
                    <td><button type="submit" class="btn btn-info">Companies(@line.WorkersInProjects.Count())</button></td>
                }
            
                @if(@line.Positions.Count() == 0)
                {
                    <td><button type="submit" class="btn btn-secondary" disabled>Positions (@line.Positions.Count())</button></td>
                }
                else
                {
                    <td><button type="submit" class="btn btn-info">Positions (@line.Positions.Count())</button></td>
                }

                @if(@line.Storages.Count() == 0)
                {
                    <td><button type="submit" class="btn btn-secondary" disabled>Storages (@line.Storages.Count())</button></td>
                }
                else
                {
                    <td><button type="submit" class="btn btn-info">Storages (@line.Storages.Count())</button></td>
                }

                @if(@line.ServerRooms.Count() == 0)
                {
                    <td class="border-info border-right"><button type="submit" class="btn btn-secondary" disabled>Server Rooms (@line.ServerRooms.Count())</button></td>
                }
                else
                {
                    <td class="border-info border-right"><button type="submit" class="btn btn-info">Server Rooms (@line.ServerRooms.Count())</button></td>
                }
            </tr>
        }
</tbody>
</table>
</div>